//=================================================================//
// Universidade Federal do Rio de Janeiro
// Escola Politécnica
// Departamento de Eletrônica e de Computação
// Professor Marcelo Luiz Drumond Lanza
// Computation II - Class 2004/2
// Authors: Carlo Fragni and Marcelo Duffles Donato Moreira
// Description: Errors header file 
// Date: 22/10/2004
//=================================================================//

/* 
 * RCS COMMENTS
 *
 * $Date: 2005/02/16 22:11:21 $
 * $Log: error.h,v $
 * Revision 1.20  2005/02/16 22:11:21  marceloddm
 * CGI's added
 *
 * Revision 1.19  2004/12/21 16:58:33  marceloddm
 * AUTENTICATE_USER__NO_USERNAME, AUTENTICATE_USER__NO_PLAIN_PASS, AUTENTICATE_USER__ERROR_OPENING_PASSWORD_FILE_FOR_READING, AUTENTICATE_USER__PASSWORD_FILE_DOES_NOT_EXIST, AUTENTICATE_USER__WRONG_PASSWORD and AUTENTICATE_USER__USERNAME_NOT_FOUND constants added
 *
 * Revision 1.18  2004/12/20 23:50:32  marceloddm
 * Constants added: VERIFY_IF_COOKIE_FILE_EXIST__ERROR_OPENING_PASSWORD_FILE_FOR_READING, VERIFY_IF_COOKIE_FILE_EXIST__PASSWORD_FILE_DOES_NOT_EXIST, VERIFY_IF_COOKIE_FILE_EXIST__USERNAME_NOT_FOUND, VERIFY_IF_COOKIE_FILE_EXIST__ERROR_OPENING_COOKIE_FILE_FOR_READING, VERIFY_IF_COOKIE_FILE_EXIST__COOKIE_FILE_DOES_NOT_EXIST, VERIFY_IF_COOKIE_FILE_EXIST__NO_USERNAME,  VERIFY_IF_COOKIE_FILE_EXIST__NO_ID, GET_COOKIE_VALUE__NO_COOKIE_NAME, GET_COOKIE_VALUE__NO_COOKIE_VALUE,  GET_COOKIE_VALUE__ERROR_OPENING_COOKIE_FILE_FOR_READING, GET_COOKIE_VALUE__COOKIE_FILE_DOES_NOT_EXIST,  CREATE_NEW_COOKIE_FILE__NO_COOKIE_NAME, CREATE_NEW_COOKIE_FILE__NO_COOKIE_VALUE,  CREATE_NEW_COOKIE_FILE__ERROR_OPENING_COOKIE_FILE_FOR_WRITING,  CREATE_NEW_COOKIE_FILE__ERROR_WRITING_EXPIRATION_IN_COOKIE_FILE,  CREATE_NEW_COOKIE_FILE__END_OF_COOKIE_FILE
 *
 * Revision 1.17  2004/12/20 12:45:51  marceloddm
 * Constants added: INSERT_FIFO__INVALID_NEW_ELEMENT, INSERT_FIFO__ERROR_ALLOCATING_MEMMORY, RETRIEVE_FIFO__INVALID_ELEMENT_DATA, , RETRIEVE_FIFO__EMPTY_FIFO, RELATIONSHIP_SYSTEM__NB_ARGS_OF_GET_USERS_OPTION, GET_USERS__INVALID_SEARCH_KEY, , GET_USERS__ERROR_OPENING_USERS_FILE_FOR_READING, GET_USERS__USERS_FILE_DOES_NOT_EXIST, GET_USERS__NO_USER_FOUND, , RELATIONSHIP_SYSTEM__NO_OPTION_SELECTED, LOGIN__FATAL_ERROR, LOGIN__MEMORY_ALLOCATION_ERROR, LOGIN__INVALID_CONTENT_LENGTH, LOGIN__CGI_IO_ERROR, LOGIN__INVALID_CONTENT_TYPE, LOGIN__INVALID_REQUEST_METHOD, , LOGIN__FORM_USERNAME_NOT_FOUND, LOGIN__INVALID_FORM_USERNAME_LENGTH, LOGIN__FORM_PLAIN_PASS_NOT_FOUND, , LOGIN__INVALID_FORM_PLAIN_PASS_LENGTH, LOGIN_INVALID_COOKIE_NAME, LOGIN_INVALID_COOKIE_VALUE, , LOGIN_INVALID_COOKIE_EXPIRATION, LOGIN_INVALID_COOKIE_NAME, LOGIN_INVALID_COOKIE_VALUE, LOGIN_INVALID_COOKIE_EXPIRATION
 *
 * Revision 1.16  2004/12/19 18:48:11  marceloddm
 * RELATIONSHIP_SYSTEM__NO_OPTION_SELECTED constant added
 *
 * Revision 1.15  2004/12/17 14:54:20  marceloddm
 * GET_DATA_FROM_ID__USER_DATA_INVAL, GET_DATA_FROM_ID__ERROR_OPENING_USERS_FILE_FOR_READING, GET_DATA_FROM_ID__USERS_FILE_DOES_NOT_EXIST, GET_DATA_FROM_ID__ERROR_OPENING_PASSWORD_FILE_FOR_READING,  GET_DATA_FROM_ID__PASSWORD_FILE_DOES_NOT_EXIST, GET_DATA_FROM_ID__USER_NOT_FOUND constants added
 *
 * Revision 1.14  2004/12/17 14:16:51  marceloddm
 * showHtmlErrorPage() function added
 *
 * Revision 1.13  2004/12/17 13:39:40  marceloddm
 * RELATIONSHIP_SYSTEM__NB_ARGS_OF_EDIT_OPTION constant added
 *
 * Revision 1.12  2004/12/17 12:11:01  marceloddm
 * The error codes from the editUserData() function were added.
 *
 * Revision 1.11  2004/12/17 01:27:09  marceloddm
 * LOGIN__IS_NOT_CGI constant added
 *
 * Revision 1.10  2004/12/15 18:24:12  marceloddm
 * Constants of copyDataToUserData() function have been removed
 *
 * Revision 1.9  2004/12/15 01:26:58  marceloddm
 * Constants added: FILL_USER_DATA__NO_USER_DATA, FILL_USER_DATA__NO_ARGV, FILL_USER_DATA__NO_PLAIN_PASS, FILL_USER_DATA__WRONG_CATEGORY, COPY_DATA_TO_USER_DATA__NO_TEMP_DATA and COPY_DATA_TO_USER_DATA__NO_USER_DATA
 *
 * Revision 1.7  2004/12/14 02:43:43  marceloddm
 * More error constants have been added like error constans of checkUserData(), backupSystemFiles() and getUserData() functions
 *
 * Revision 1.6  2004/12/13 16:00:52  marceloddm
 * Updated with checkUserData() and putUserData() functions
 *
 * Revision 1.5  2004/12/13 07:45:06  marceloddm
 * More constants have been added
 *
 * Revision 1.4  2004/12/11 12:34:05  marceloddm
 * Author changed for 'marceloddm'
 *
 * Revision 1.3  2004/11/30 00:26:23  root
 *  Last modification: checkField()'s contants
 *
 * Revision 1.2  2004/11/26 13:40:19  root
 * RCS's strings added
 *
 */ 
 
#ifndef _ERROR_H_
#define _ERROR_H_ "@(#)error.h $Revision: 1.20 $"

#undef  OK
#define OK 					    									0
#define CREATE_RANDOM_STRING__INVALID_STRING        									1
#define CREATE_RANDOM_STRING__NO_VALID_CHARACTERS   									2
#define INV_ARGS		 	  	    									3
#define ENCODE_PASSWORD__INVALID_ENCRYPTED_PASS    									4
#define ENCODE_PASSWORD__INVALID_PLAIN_PASS        									5
#define CHECK_PASSWORD__INVALID_PLAIN_PASS	    									6
#define CHECK_PASSWORD__INVALID_ENCRYPTED_PASS	    									7
#define CHECK_PASSWORD__WRONG_PLAIN_PASS	    									8
#define GET_LONG_FILENAME__INVALID_PATH		    									9 
#define GET_LONG_FILENAME__INVALID_FILENAME	    									10
#define GET_LONG_FILENAME__NO_LONG_FILENAME	    									11
#define GET_LONG_FILENAME__INVALID_LONG_FILENAME    									12
#define GET_USER_ID__INVALID_FILE		    									13
#define GET_USER_ID__INVALID_USER_ID		    									14
#define GET_USER_ID__ERROR_READING_FILE		    									15
#define GET_USER_ID__END_OF_FILE		    									16
#define GET_STRING__INVALID_FILE		    									17
#define GET_STRING__INVALID_STRING		    									18
#define GET_STRING__ERROR_READING_FILE		    									19
#define GET_STRING__END_OF_FILE			    									20
#define GET_STRING__SMALL_STRING		    									21
#define GET_STRING__BIG_STRING			    									22
#define CHECK_FIELD__INVALID_FIELD		    									23
#define CHECK_FIELD__NO_VALID_CHARACTERS	    									24
#define CHECK_FIELD__SMALL_FIELD		    									25
#define CHECK_FIELD__BIG_FIELD												26
#define CHECK_FIELD__FIELD_HAS_NOT_VALID_CHARACTERS									27
#define GET_ADMINISTRATOR_PASSWORD__DO_NOT_IS_THE_ADMINISTRATOR 							28
#define GET_ADMINISTRATOR_PASSWORD__INVALID_PASSWORD									29
#define GET_ADMINISTRATOR_PASSWORD__LOGIN_INCORRECT									30
#define INSTALL__INVALID_USER_DATA											31
#define RELATIONSHIP_SYSTEM__MORE_THAN_ONE_OPTION									32
#define INSTALL__SYSTEM_ALREADY_INSTALLED										33
#define INSTALL__ERROR_READING_PASSWORD_FILE										34
#define INSTALL__ERROR_OPENING_PASSWORD_FILE_FOR_WRITING								35
#define PUT_USER_ID__INVALID_FILE											36
#define PUT_USER_ID__INVALID_USER_ID											37
#define PUT_USER_ID__ERROR_WRITING_FILE											38
#define PUT_USER_ID__END_OF_FILE											39
#define PUT_STRING__INVALID_FILE											40
#define PUT_STRING__INVALID_STRING											41
#define PUT_STRING__ERROR_WRITING_FILE											42
#define PUT_STRING__END_OF_FILE												43
#define PUT_STRING__SMALL_STRING											44
#define PUT_STRING__BIG_STRING												45
#define PUT_USER_CATEGORY__INVALID_FILE											46
#define PUT_USER_CATEGORY__INVALID_USER_CATEGORY									47
#define PUT_USER_CATEGORY__ERROR_WRITING_FILE										48
#define PUT_USER_CATEGORY__END_OF_FILE											49
#define PUT_USER_GENDER__INVALID_FILE											50
#define PUT_USER_GENDER__INVALID_USER_GENDER										51
#define PUT_USER_GENDER__ERROR_WRITING_FILE										52
#define PUT_USER_GENDER__END_OF_FILE											53
#define PUT_USER_RELATIONSHIP_STATUS__INVALID_FILE									54
#define PUT_USER_RELATIONSHIP_STATUS__INVALID_USER_RELATIONSHIP_STATUS							55
#define PUT_USER_RELATIONSHIP_STATUS__ERROR_WRITING_FILE								56
#define PUT_USER_RELATIONSHIP_STATUS__END_OF_FILE									57
#define INSTALL__ERROR_READING_USERS_FILE										58
#define INSTALL__ERROR_OPENING_USERS_FILE_FOR_WRITING									59
#define INSTALL__ERROR_READING_PARENTS_FILE										60
#define INSTALL__ERROR_OPENING_PARENTS_FILE_FOR_WRITING									61
#define INSTALL__ERROR_READING_FRIENDS_FILE										62
#define INSTALL__ERROR_OPENING_FRIENDS_FILE_FOR_WRITING									63
#define CHECK_USER_DATA__INVALID_USER_DATA										64
#define PUT_USER_DATA__INVALID_FILE											65
#define PUT_USER_DATA__NO_FILENAME											66
#define PUT_USER_DATA__INVALID_USER_DATA										67
#define PUT_USER_DATA__INVALID_FILENAME											68
#define GET_USER_CATEGORY__INVALID_FILE											69
#define GET_USER_CATEGORY__INVALID_USER_CATEGORY									70
#define GET_USER_CATEGORY__ERROR_READING_FILE										71
#define GET_USER_CATEGORY__END_OF_FILE											72
#define GET_USER_GENDER__INVALID_FILE											73
#define GET_USER_GENDER__INVALID_USER_GENDER										74
#define GET_USER_GENDER__ERROR_READING_FILE										75
#define GET_USER_GENDER__END_OF_FILE											76
#define GET_USER_RELATIONSHIP_STATUS__INVALID_FILE									77
#define GET_USER_RELATIONSHIP_STATUS__INVALID_USER_RELATIONSHIP_STATUS							78
#define GET_USER_RELATIONSHIP_STATUS__ERROR_READING_FILE								79
#define GET_USER_RELATIONSHIP_STATUS__END_OF_FILE									80
#define GET_USER_DATA__INVALID_FILE											81
#define GET_USER_DATA__NO_FILENAME											82
#define GET_USER_DATA__INVALID_USER_DATA										83
#define GET_USER_DATA__INVALID_FILENAME											84
#define RELATIONSHIP_SYSTEM__ERROR_OPENING_PASSWORD_FILE_FOR_READING							85
#define RELATIONSHIP_SYSTEM__NOT_YET_INSTALLED										86
#define BACKUP_SYSTEM_FILES__ERROR_OPENING_PASSWORD_FILE_FOR_READING							87
#define BACKUP_SYSTEM_FILES__ERROR_OPENING_USERS_FILE_FOR_READING							88
#define BACKUP_SYSTEM_FILES__ERROR_OPENING_FRIENDS_FILE_FOR_READING							89
#define BACKUP_SYSTEM_FILES__ERROR_OPENING_PARENTS_FILE_FOR_READING							90
#define BACKUP_SYSTEM_FILES__NOT_YET_INSTALLED										91
#define CHECK_USER_DATA__USERNAME_HAS_NOT_VALID_CHARACTERS								92
#define CHECK_USER_DATA__BIG_USERNAME											93
#define CHECK_USER_DATA__SMALL_USERNAME											94
#define CHECK_USER_DATA__PLAIN_PASS_HAS_NOT_VALID_CHARACTERS								95
#define CHECK_USER_DATA__BIG_PLAIN_PASS											96
#define CHECK_USER_DATA__SMALL_PLAIN_PASS										97
#define CHECK_USER_DATA__ENCRYPTED_PASS_HAS_NOT_VALID_CHARACTERS							98
#define CHECK_USER_DATA__BIG_ENCRYPTED_PASS										99
#define CHECK_USER_DATA__SMALL_ENCRYPTED_PASS										100
#define CHECK_USER_DATA__NAME_HAS_NOT_VALID_CHARACTERS									101
#define CHECK_USER_DATA__BIG_NAME											102
#define CHECK_USER_DATA__SMALL_NAME											103
#define CHECK_USER_DATA__EMAIL_HAS_NOT_VALID_CHARACTERS									104
#define CHECK_USER_DATA__BIG_EMAIL											105
#define CHECK_USER_DATA__SMALL_EMAIL											106
#define CHECK_USER_DATA__HOMEPAGE_HAS_NOT_VALID_CHARACTERS								107
#define CHECK_USER_DATA__BIG_HOMEPAGE											108
#define CHECK_USER_DATA__SMALL_HOMEPAGE											109
#define CHECK_USER_DATA__TEL_NUMBER_HAS_NOT_VALID_CHARACTERS								110
#define CHECK_USER_DATA__BIG_TEL_NUMBER											111
#define CHECK_USER_DATA__SMALL_TEL_NUMBER										112
#define CHECK_USER_DATA__CELL_NUMBER_HAS_NOT_VALID_CHARACTERS								113
#define CHECK_USER_DATA__BIG_CELL_NUMBER										114
#define CHECK_USER_DATA__SMALL_CELL_NUMBER										115
#define CHECK_USER_DATA__BIRTHDAY_HAS_NOT_VALID_CHARACTERS								116
#define CHECK_USER_DATA__BIG_BIRTHDAY											117
#define CHECK_USER_DATA__SMALL_BIRTHDAY											118
#define CHECK_USER_DATA__DESCRIPTION_HAS_NOT_VALID_CHARACTERS								119
#define CHECK_USER_DATA__BIG_DESCRIPTION										120
#define CHECK_USER_DATA__SMALL_DESCRIPTION										121
#define CHECK_USER_DATA__STREET_HAS_NOT_VALID_CHARACTERS								122
#define CHECK_USER_DATA__BIG_STREET											123
#define CHECK_USER_DATA__SMALL_STREET											124
#define CHECK_USER_DATA__HOME_NUMBER_HAS_NOT_VALID_CHARACTERS								125
#define CHECK_USER_DATA__BIG_HOME_NUMBER										126
#define CHECK_USER_DATA__SMALL_HOME_NUMBER										127
#define CHECK_USER_DATA__COMPLEMENT_HAS_NOT_VALID_CHARACTERS								128
#define CHECK_USER_DATA__BIG_COMPLEMENT											129
#define CHECK_USER_DATA__SMALL_COMPLEMENT										130
#define CHECK_USER_DATA__DISTRICT_HAS_NOT_VALID_CHARACTERS								131
#define CHECK_USER_DATA__BIG_DISTRICT											132
#define CHECK_USER_DATA__SMALL_DISTRICT											133
#define CHECK_USER_DATA__CITY_HAS_NOT_VALID_CHARACTERS									134
#define CHECK_USER_DATA__BIG_CITY											135
#define CHECK_USER_DATA__SMALL_CITY											136
#define CHECK_USER_DATA__STATE_HAS_NOT_VALID_CHARACTERS									137
#define CHECK_USER_DATA__BIG_STATE											138
#define CHECK_USER_DATA__SMALL_STATE											139
#define CHECK_USER_DATA__COUNTRY_HAS_NOT_VALID_CHARACTERS								140
#define CHECK_USER_DATA__BIG_COUNTRY											141
#define CHECK_USER_DATA__SMALL_COUNTRY											142
#define CHECK_USER_DATA__ZIP_CODE_HAS_NOT_VALID_CHARACTERS								143
#define CHECK_USER_DATA__BIG_ZIP_CODE											144
#define CHECK_USER_DATA__SMALL_ZIP_CODE											145
#define RELATIONSHIP_SYSTEM__NB_ARGS_OF_INSTALL_OPTION									146
#define FILL_USER_DATA__NO_USER_DATA											147
#define FILL_USER_DATA__NO_ARGV												148
#define FILL_USER_DATA__NO_PLAIN_PASS											149
#define FILL_USER_DATA__WRONG_CATEGORY											150
#define IS_NOT_CGI													151
#define EDIT_USER_DATA__ERROR_OPENING_USERS_FILE_FOR_READING								152    
#define EDIT_USER_DATA__USERS_FILE_DOES_NOT_EXIST									153
#define EDIT_USER_DATA__ERROR_OPENING_TEMP_FILE_FOR_WRITING								154
#define EDIT_USER_DATA__NAME_AND_BIRTHDAY_ALREADY_EXIST									155
#define EDIT_USER_DATA__ERROR_WRITING_IN_TEMP_FILE									156
#define EDIT_USER_DATA__USER_NOT_FOUND											157
#define RELATIONSHIP_SYSTEM__NB_ARGS_OF_EDIT_OPTION									158
#define COPY_USER_DATA__DATA_IN_INVAL											159
#define COPY_USER_DATA__DATA_OUT_INVAL											160
#define GET_DATA_FROM_ID__USER_DATA_INVAL										161
#define GET_DATA_FROM_ID__ERROR_OPENING_USERS_FILE_FOR_READING								162
#define GET_DATA_FROM_ID__USERS_FILE_DOES_NOT_EXIST									163
#define GET_DATA_FROM_ID__ERROR_OPENING_PASSWORD_FILE_FOR_READING							164
#define GET_DATA_FROM_ID__PASSWORD_FILE_DOES_NOT_EXIST									165
#define GET_DATA_FROM_ID__USER_NOT_FOUND										166
#define INSERT_FIFO__INVALID_NEW_ELEMENT										167 
#define INSERT_FIFO__ERROR_ALLOCATING_MEMMORY										168
#define RETRIEVE_FIFO__INVALID_ELEMENT_DATA										169
#define RETRIEVE_FIFO__EMPTY_FIFO											170  
#define RELATIONSHIP_SYSTEM__NB_ARGS_OF_GET_USERS_OPTION								171
#define GET_USERS__INVALID_SEARCH_KEY											172
#define GET_USERS__ERROR_OPENING_USERS_FILE_FOR_READING									173
#define GET_USERS__USERS_FILE_DOES_NOT_EXIST										174
#define GET_USERS__NO_USER_FOUND											175
#define RELATIONSHIP_SYSTEM__NO_OPTION_SELECTED										176
#define FATAL_ERROR												177
#define MEMORY_ALLOCATION_ERROR											178
#define INVALID_CONTENT_LENGTH											179
#define CGI_IO_ERROR												180
#define INVALID_CONTENT_TYPE											181
#define INVALID_REQUEST_METHOD											182
#define FORM_USERNAME_NOT_FOUND											183
#define INVALID_FORM_USERNAME_LENGTH										184
#define FORM_PLAIN_PASS_NOT_FOUND										185
#define INVALID_FORM_PLAIN_PASS_LENGTH										186
#define INVALID_COOKIE_NAME											187
#define INVALID_COOKIE_VALUE											188
#define INVALID_COOKIE_EXPIRATION											189
#define VERIFY_IF_COOKIE_FILE_EXIST__ERROR_OPENING_PASSWORD_FILE_FOR_READING						190
#define VERIFY_IF_COOKIE_FILE_EXIST__PASSWORD_FILE_DOES_NOT_EXIST							191
#define VERIFY_IF_COOKIE_FILE_EXIST__USERNAME_NOT_FOUND									192
#define VERIFY_IF_COOKIE_FILE_EXIST__ERROR_OPENING_COOKIE_FILE_FOR_READING						193
#define VERIFY_IF_COOKIE_FILE_EXIST__COOKIE_FILE_DOES_NOT_EXIST								194
#define VERIFY_IF_COOKIE_FILE_EXIST__NO_USERNAME									195
#define VERIFY_IF_COOKIE_FILE_EXIST__NO_ID										196
#define GET_COOKIE_VALUE__NO_COOKIE_NAME										197
#define GET_COOKIE_VALUE__NO_COOKIE_VALUE										198
#define GET_COOKIE_VALUE__ERROR_OPENING_COOKIE_FILE_FOR_READING								199
#define GET_COOKIE_VALUE__COOKIE_FILE_DOES_NOT_EXIST									200
#define CREATE_NEW_COOKIE_FILE__NO_COOKIE_NAME										201
#define CREATE_NEW_COOKIE_FILE__NO_COOKIE_VALUE										202
#define CREATE_NEW_COOKIE_FILE__ERROR_OPENING_COOKIE_FILE_FOR_WRITING							203
#define CREATE_NEW_COOKIE_FILE__ERROR_WRITING_EXPIRATION_IN_COOKIE_FILE							204
#define CREATE_NEW_COOKIE_FILE__END_OF_COOKIE_FILE									205
#define AUTENTICATE_USER__NO_USERNAME											206
#define AUTENTICATE_USER__NO_PLAIN_PASS											207
#define AUTENTICATE_USER__ERROR_OPENING_PASSWORD_FILE_FOR_READING							208
#define AUTENTICATE_USER__PASSWORD_FILE_DOES_NOT_EXIST									209
#define AUTENTICATE_USER__USERNAME_NOT_FOUND										210
#define ADD_USER__ERROR_OPENING_USERS_FILE_FOR_READING									211
#define ADD_USER__ERROR_OPENING_PASSWORD_FILE_FOR_READING								212
#define ADD_USER__USERS_FILE_DOES_NOT_EXIST										213
#define ADD_USER__PASSWORD_FILE_DOES_NOT_EXIST										214
#define ADD_USER__ERROR_OPENING_USERS_TEMP_FILE_FOR_WRITING								215
#define ADD_USER__ERROR_OPENING_PASSWORD_TEMP_FILE_FOR_WRITING								216
#define ADD_USER__USER_ALREADY_EXIST											217
#define ADD_USER__ERROR_WRITING_IN_USERS_TEMP_FILE									218
#define ADD_USER__ERROR_WRITING_IN_PASSWORD_TEMP_FILE									219
#define RELATIONSHIP_SYSTEM__WRONG_NB_ARGS_OF_ADD_OPTION								220
#define RELATIONSHIP_SYSTEM__LOGIN_INCORRECT_OF_NEW_USER								221
#define ACCEPT_FRIENDSHIP_INVITATION__ERROR_OPENING_INVITED_FRIEND_IN_FILE_FOR_READING					222
#define ACCEPT_FRIENDSHIP_INVITATION__INVITED_FRIEND_IN_FILE_DOES_NOT_EXIST						223
#define ACCEPT_FRIENDSHIP_INVITATION__ERROR_OPENING_INVITED_FRIEND_IN_TEMP_FILE_FOR_WRITTING				224
#define ACCEPT_FRIENDSHIP_INVITATION__INVITED_FRIEND_IN_FILE_DOES_NOT_HAVE_INVITATION_FROM_GIVEN_INVITING_FRIEND	225
#define ACCEPT_FRIENDSHIP_INVITATION__ERROR_OPENING_INVITING_FRIEND_OUT_FILE_FOR_READING				226
#define ACCEPT_FRIENDSHIP_INVITATION__INVITING_FRIEND_OUT_FILE_DOES_NOT_EXIST						227
#define ACCEPT_FRIENDSHIP_INVITATION__ERROR_OPENING_INVITING_FRIEND_OUT_TEMP_FILE_FOR_WRITTING				228
#define ACCEPT_FRIENDSHIP_INVITATION__INVITING_FRIEND_OUT_FILE_DOES_NOT_HAVE_INVITATION_TO_GIVEN_INVITED_FRIEND		229
#define ACCEPT_FRIENDSHIP_INVITATION__ERROR_OPENING_FRIENDS_FILE_FOR_READING						230
#define ACCEPT_FRIENDSHIP_INVITATION__FRIENDS_FILE_DOES_NOT_EXIST							231
#define ACCEPT_FRIENDSHIP_INVITATION__ERROR_OPENING_FRIENDS_TEMP_FILE_FOR_WRITING					232
#define ACCEPT_FRIENDSHIP_INVITATION__FRIENDSHIP_ALREADY_EXISTS								233
#define RELATIONSHIP_SYSTEM__WRONG_NB_ARGS_OF_ACCEPT_OPTION								234
#define ADD_USER__USERNAME_ALREADY_EXIST										235
#define ADD_USER__ERROR_OPENING_IN_FILE_FOR_WRITING									236
#define ADD_USER__ERROR_OPENING_OUT_FILE_FOR_WRITING									237
#define REJECT_FRIENDSHIP_INVITATION__ERROR_OPENING_INVITED_FRIEND_IN_FILE_FOR_READING					238
#define REJECT_FRIENDSHIP_INVITATION__INVITED_FRIEND_IN_FILE_DOES_NOT_EXIST						239
#define REJECT_FRIENDSHIP_INVITATION__ERROR_OPENING_INVITED_FRIEND_IN_TEMP_FILE_FOR_WRITTING				240
#define REJECT_FRIENDSHIP_INVITATION__INVITED_FRIEND_IN_FILE_DOES_NOT_HAVE_INVITATION_FROM_GIVEN_INVITING_FRIEND	241
#define REJECT_FRIENDSHIP_INVITATION__ERROR_OPENING_INVITING_FRIEND_OUT_FILE_FOR_READING				242
#define REJECT_FRIENDSHIP_INVITATION__INVITING_FRIEND_OUT_FILE_DOES_NOT_EXIST						243
#define REJECT_FRIENDSHIP_INVITATION__ERROR_OPENING_INVITING_FRIEND_OUT_TEMP_FILE_FOR_WRITTING				244
#define REJECT_FRIENDSHIP_INVITATION__INVITING_FRIEND_OUT_FILE_DOES_NOT_HAVE_INVITATION_TO_GIVEN_INVITED_FRIEND		245
#define INSTALL__ERROR_OPENING_IN_FILE_FOR_WRITING									246
#define INSTALL__ERROR_OPENING_OUT_FILE_FOR_WRITING									247
#define RELATIONSHIP_SYSTEM__WRONG_NB_ARGS_OF_REJECT_OPTION								248
#define CREATE_NEW_COOKIE_FILE__NO_IP											249
#define NCURSES__ERROR_INITIALIZING_NCURSES										250
#define NCURSES__ERROR_DISABLING_LINE_BUFFERING										251
#define NCURSES__ERROR_DISABLING_ECHO											252
#define NCURSES__ERROR_ENABLING_KEYPAD											253
#define NCURSES__MEMORY_ALLOCATION_ERROR										254
#define NCURSES__ERROR_CREATING_NEW_MENU_ITEM										255
#define NCURSES__ERROR_CREATING_NEW_MENU										256
#define NCURSES__ERROR_POSTING_MENU											257
#define NCURSES__ERROR_REFRESHING_TERMINAL										258
#define NCURSES__ERROR_IN_MENU_DRIVER_FUNCTION										259
#define NCURSES__ERROR_FREEING_MEMORY_ALLOCATED_TO_MENU_ITEMS								260
#define NCURSES__ERROR_FREEING_MEMORY_ALLOCATED_TO_MENU									261
#define NCURSES__ERROR_FINALIZING_NCURSES										262
#define NCURSES__ERROR_UNPOSTING_MENU											263
#define RECOVERY_PASSWORD__ERROR_OPENING_PASSWORD_FILE_FOR_READING							264
#define RECOVERY_PASSWORD__PASSWORD_FILE_DOES_NOT_EXIST									265
#define RECOVERY_PASSWORD__ERROR_OPENING_PASSWORD_TEMP_FILE_FOR_WRITTING						266
#define RECOVERY_PASSWORD__USER_NOT_FOUND										267
#define RELATIONSHIP_SYSTEM__WRONG_NB_ARGS_OF_EXCLUDE_OPTION								268
#define INVITE_FRIEND__ERROR_OPENING_INVITED_FRIEND_IN_FILE_FOR_READING							269
#define INVITE_FRIEND__INVITED_FRIEND_IN_FILE_DOES_NOT_EXIST								270
#define INVITE_FRIEND__ERROR_OPENING_INVITED_FRIEND_IN_TEMP_FILE_FOR_WRITTING						271
#define INVITE_FRIEND__THERE_IS_ALREADY_AN_INVITATION_IN_THE_INVITED_FRIEND_IN_FILE					272
#define INVITE_FRIEND__ERROR_OPENING_INVITING_FRIEND_OUT_FILE_FOR_READING						273
#define INVITE_FRIEND__INVITING_FRIEND_OUT_FILE_DOES_NOT_EXIST								274
#define INVITE_FRIEND__ERROR_OPENING_INVITING_FRIEND_OUT_TEMP_FILE_FOR_WRITTING						275
#define INVITE_FRIEND__THERE_IS_ALREADY_AN_INVITATION_IN_THE_INVITING_FRIEND_OUT_FILE					276
#define INVITE_FRIEND__ERROR_OPENING_FRIENDS_FILE_FOR_READING								277
#define INVITE_FRIEND__FRIENDS_FILE_DOES_NOT_EXIST									278
#define INVITE_FRIEND__FRIENDSHIP_ALREADY_EXISTS									279
#define RELATIONSHIP_SYSTEM__WRONG_NB_ARGS_OF_INVITE_FRIEND_OPTION							280
#define RELATIONSHIP_SYSTEM__NB_ARGS_OF_RECOVERY_OPTION									281
#define EXCLUDE_FRIEND__ERROR_OPENING_FRIENDS_FILE_FOR_READING								282
#define EXCLUDE_FRIEND__FRIENDS_FILE_DOES_NOT_EXIST									283
#define EXCLUDE_FRIEND__ERROR_OPENING_FRIENDS_TEMP_FILE_FOR_WRITING							284
#define EXCLUDE_FRIEND__THE_TWO_GIVEN_USERS_WERE_NOT_FRIENDS								285
#define NCURSES__ERROR_SETTING_MENU_FORMAT										286
#define NCURSES__ERROR_REFRESHING_MENU_WINDOW										287
#define NCURSES__ERROR_SETTING_COLORS											288
#define NCURSES__ERROR_CREATING_MENU_SUB_WINDOW										289
#define NCURSES__ERROR_CREATING_MENU_WINDOW										290
#define NCURSES__ERROR_SETTING_MENU_WINDOW										291
#define NCURSES__ERROR_SETTING_MENU_SUB_WINDOW										292
#define NCURSES__ERROR_CREATING_MENU_BORDER										293
#define GET_FRIENDS__ERROR_OPENING_FRIENDS_FILE_FOR_READING								294
#define GET_FRIENDS__FRIENDS_FILE_DOES_NOT_EXIST									295
#define GET_FRIENDS__NO_FRIENDS_FOUND											296
#define RELATIONSHIP_SYSTEM__WRONG_NB_ARGS_OF_GET_FRIENDS_OPTION							297
#define NCURSES__ERROR_CREATING_FORM_FIELDS										298
#define NCURSES__ERROR_FREEING_MEMORY_ALLOCATED_TO_FORM_FIELDS								299
#define NCURSES__ERROR_FREEING_MEMORY_ALLOCATED_TO_FORM									300
#define INVITE_FRIEND__CANNOT_INVITE_THE_OWN_USER									301
#define INVITE_FRIEND__ERROR_OPENING_INVITED_FRIEND_OUT_FILE_FOR_READING						302
#define INVITE_FRIEND__INVITED_FRIEND_OUT_FILE_DOES_NOT_EXIST								303
#define	INVITE_FRIEND__THERE_IS_ALREADY_AN_INVITATION_TO_THE_INVITING_FRIEND_IN_THE_INVITED_FRIEND_OUT_FILE			304
#define INVITE_FRIEND__ERROR_OPENING_INVITING_FRIEND_IN_FILE_FOR_READING						305
#define INVITE_FRIEND__INVITING_FRIEND_IN_FILE_DOES_NOT_EXIST								306
#define INVITE_FRIEND__THERE_IS_ALREADY_AN_INVITATION_FROM_THE_INVITED_FRIEND_IN_THE_INVITING_FRIEND_IN_FILE		307
#define REPAIR_FORM_DATA__NO_USER_DATA											308
#define REPAIR_FORM_DATA__NO_FORM_FIELDS										309
#define REPAIR_FORM_DATA__UNKNOWN_OPTION										310
#define ADD_PARENT_RELATIONSHIP__GIVEN_PARENT_HAS_NO_GENDER_ANSWERED							311
#define ADD_PARENT_RELATIONSHIP__ERROR_OPENING_PARENTS_FILE_FOR_READING							312
#define ADD_PARENT_RELATIONSHIP__PARENTS_FILE_DOES_NOT_EXIST								313
#define ADD_PARENT_RELATIONSHIP__ERROR_OPENING_PARENTS_TEMP_FILE_FOR_WRITING						314
#define ADD_PARENT_RELATIONSHIP__USER_ALREADY_HAS_A_FATHER								315
#define ADD_PARENT_RELATIONSHIP__USER_ALREADY_HAS_A_MOTHER								316
#define ADD_PARENT_RELATIONSHIP__GIVEN_PERSON_IS_ALREADY_PARENT_OF_THE_GIVEN_USER					317
#define NCURSES__ERROR_CREATING_FORM											318
#define NCURSES__ERROR_POSTING_FORM											319
#define NCURSES__ERROR_IN_FORM_DRIVER_FUNCTION										320
#define NCURSES__ERROR_UNPOSTING_FORM											321
#define CHANGE_USER_CATEGORY__ERROR_OPENING_PASSWORD_FILE_FOR_READING							322
#define CHANGE_USER_CATEGORY__PASSWORD_FILE_DOES_NOT_EXIST								323
#define CHANGE_USER_CATEGORY__ERROR_OPENING_TEMP_FILE_FOR_WRITING							324
#define RELATIONSHIP_SYSTEM__WRONG_NB_ARGS_OF_ADD_PARENT_OPTION								325
#define RELATIONSHIP_SYSTEM__WRONG_NB_ARGS_OF_CHANGE_CATEGORY_OPTION							326
#define CHANGE_PASSWORD__ERROR_OPENING_PASSWORD_FILE_FOR_READING							327
#define CHANGE_PASSWORD__PASSWORD_FILE_DOES_NOT_EXIST									328
#define CHANGE_PASSWORD__ERROR_OPENING_PASSWORD_TEMP_FILE_FOR_WRITTING							329
#define CHANGE_PASSWORD__USER_NOT_FOUND											330
#define REPAIR_FORM_DATA__INVALID_CATEGORY										331
#define CHANGE_USER_CATEGORY__CAN_NOT_CHANGE_ADMINISTRATOR_CATEGORY							332
#define EDIT_PARENT_RELATIONSHIP__GIVEN_PARENT_HAS_NO_GENDER_ANSWERED							333
#define EDIT_PARENT_RELATIONSHIP__NO_CHANGES_IN_RELATIONSHIP_REQUIRED							334
#define EDIT_PARENT_RELATIONSHIP_OLD_PARENT_AND_NEW_PARENT_HAVE_OTHER_SEX						335
#define EDIT_PARENT_RELATIONSHIP__ERROR_OPENING_PARENTS_FILE_FOR_READING						336
#define EDIT_PARENT_RELATIONSHIP__PARENTS_FILE_DOES_NOT_EXIST								337
#define EDIT_PARENT_RELATIONSHIP__ERROR_OPENING_PARENTS_TEMP_FILE_FOR_WRITING   					338
#define EDIT_PARENT_RELATIONSHIP__GIVEN_OLD_RELATIONSHIP_NOT_FOUND							339
#define GET_FRIENDSHIP_INVITATION__ERROR_OPENING_USER_IN_FILE_FOR_READING						340
#define GET_FRIENDSHIP_INVITATION__USER_IN_FILE_DOES_NOT_EXIST								341
#define GET_FRIENDSHIP_INVITATION__NO_INVITATIONS_FOUND									342
#define INVITE_USER__ERROR_OPENING_INVITED_USER_FILE_FOR_WRITING 							343
#define REMOVE_USER__CANNOT_REMOVE_ADMINISTRATOR									344
#define REMOVE_USER__ERROR_OPENING_USERS_FILE_FOR_READING								345
#define REMOVE_USER__USERS_FILE_DOES_NOT_EXIST										346
#define REMOVE_USER__ERROR_OPENING_USERS_TEMP_FILE_FOR_WRITTING								347
#define REMOVE_USER__USER_NOT_FOUND											348
#define REMOVE_USER__ERROR_OPENING_PASSWORD_FILE_FOR_READING								349
#define REMOVE_USER__PASSWORD_FILE_DOES_NOT_EXIST									350
#define REMOVE_USER__ERROR_OPENING_PASSWORD_TEMP_FILE_FOR_WRITTING							351
#define REMOVE_PARENT_RELATIONSHIP__ERROR_OPENING_PARENTS_FILE_FOR_READING						352 
#define REMOVE_PARENT_RELATIONSHIP__PARENTS_FILE_DOES_NOT_EXIST								353
#define REMOVE_PARENT_RELATIONSHIP__ERROR_OPENING_PARENTS_TEMP_FILE_FOR_WRITING						354
#define REMOVE_PARENT_RELATIONSHIP__GIVEN_PARENT_RELATIONSHIP_NOT_FOUND  						355
#define RELATIONSHIP_SYSTEM__WRONG_NB_ARGS_OF_REMOVE_USER_OPTION							356
#define RELATIONSHIP_SYSTEM__WRONG_NB_ARGS_OF_INVITE_USER_OPTION							357
#define RELATIONSHIP_SYSTEM__WRONG_NB_ARGS_OF_GET_FRIENDSHIP_INVITATION_OPTION						358
#define RELATIONSHIP_SYSTEM__WRONG_NB_ARGS_OF_REMOVE_PARENT_OPTION							359
#define RELATIONSHIP_SYSTEM__WRONG_NB_ARGS_OF_EDIT_PARENT_OPTION							360
#define RELATIONSHIP_SYSTEM__NB_ARGS_OF_CHANGE_PASSWORD_OPTION								361
#define RELATIONSHIP_SYSTEM__CONFIRMATION_DOES_NOT_MATCH								362
#define INVITE_USER__USER_HAS_ALREADY_BEEN_INVITED									363
#define CHANGE_USER_CATEGORY__ERROR_OPENING_USERS_FILE_FOR_READING							364
#define CHANGE_USER_CATEGORY__USERS_FILE_DOES_NOT_EXIST									365
#define CHANGE_USER_CATEGORY__ERROR_OPENING_IN_FILE_FOR_WRITING								366
#define CHANGE_USER_CATEGORY__ERROR_OPENING_OUT_FILE_FOR_WRITING							367
#define INVITE_FRIEND__RELATIVES_CAN_NOT_INVITE_FRIENDS									368
#define INVITE_FRIEND__RELATIVES_CAN_NOT_BE_INVITED									369
#define GET_FRIENDSHIP_INVITATION__RELATIVES_HAVE_NOT_INVITATIONS							370
#define COOKIE_NOT_FOUND												371
#define VALIDATE_COOKIE__NO_COOKIE_NAME											372
#define VALIDATE_COOKIE__NO_COOKIE_VALUE										373
#define VALIDATE_COOKIE__NO_IP												374
#define VALIDATE_COOKIE__ERROR_OPENING_COOKIE_FILE_FOR_READING								375
#define VALIDATE_COOKIE__COOKIE_FILE_DOES_NOT_EXIST									376
#define VALIDATE_COOKIE__WRONG_COOKIE_VALUE										377
#define VALIDATE_COOKIE__ERROR_READING_EXPIRATION_IN_COOKIE_FILE							378
#define VALIDATE_COOKIE__END_OF_COOKIE_FILE										379
#define VALIDATE_COOKIE__COOKIE_HAS_EXPIRED										380
#define VALIDATE_COOKIE__WRONG_IP											381
#define ERROR_SENDING_EMAIL												382
#define INVALID_FORM_FIELD_LENGTH											383
#define FORM_FIELD_NOT_FOUND												384
#define ONLY_THE_ADMINISTRATOR_CAN_EDIT_DATA_OF_OTHERS_USERS								385
#define ONLY_THE_ADMINISTRATOR_CAN_REMOVE_OTHERS_USERS									386
#define YOU_CAN_ONLY_INVITE_USERS_BY_YOURSELF										387
#define YOU_CAN_ONLY_INVITE_FRIENDS_BY_YOURSELF										388
#define YOU_CAN_ONLY_GET_YOURS_PENDING_INVITATIONS									389
#define YOU_CAN_ONLY_ACCEPT_YOURS_INVITATIONS										390
#define YOU_CAN_ONLY_REJECT_YOURS_INVITATIONS										391
#define YOU_CAN_ONLY_EXCLUDE_YOURS_FRIENDS										392
#define ONLY_THE_ADMINISTRATOR_CAN_GET_FRIENDS_OF_OTHERS_USERS								393
#define ONLY_THE_ADMINISTRATOR_CAN_CHANGE_CATEGORY_OF_OTHERS_USERS							394
#define YOU_CAN_ONLY_ADD_PARENTS_FOR_YOU										395
#define YOU_CAN_ONLY_REMOVE_PARENTS_FOR_YOU										396
#define YOU_CAN_ONLY_EDIT_YOUR_PARENT_RELATIONSHIP									397
#define ONLY_THE_ADMINISTRATOR_CAN_RECOVERY_PASSWORD_OF_OTHERS_USERS							398
#define ONLY_THE_ADMINISTRATOR_CAN_CHANGE_PASSWORD_OF_OTHERS_USERS							399
#define USER_HAS_REJECTED_THE_INVITATION										400
#define ERROR_OPENING_TEMPORARY_FILE_FOR_READING									401
#define TEMPORARY_FILE_DOES_NOT_EXIST											402
#define NCURSES__ERROR_SIZE_SMALLER_THAN_RECOMMENDED									403
#define GET_DATA_FROM_USERNAME__NO_USERNAME										404
#define GET_DATA_FROM_USERNAME__NO_USER_DATA										405
#define GET_DATA_FROM_USERNAME__ERROR_OPENING_USERS_FILE_FOR_READING							406
#define GET_DATA_FROM_USERNAME__USERS_FILE_DOES_NOT_EXIST								407
#define GET_DATA_FROM_USERNAME__ERROR_OPENING_PASSWORD_FILE_FOR_READING							408
#define GET_DATA_FROM_USERNAME__PASSWORD_FILE_DOES_NOT_EXIST								409
#define GET_DATA_FROM_USERNAME__USER_NOT_FOUND										410
#define FORM_USER_ID_NOT_FOUND												411
#define INVALID_FORM_USER_ID_LENGTH											412
#define FORM_NAME_NOT_FOUND												413
#define INVALID_FORM_NAME_LENGTH											414
#define FORM_EMAIL_NOT_FOUND												415
#define INVALID_FORM_EMAIL_LENGTH											416
#define FORM_HOMEPAGE_NOT_FOUND												417
#define INVALID_FORM_HOMEPAGE_LENGTH											418
#define FORM_STREET_NOT_FOUND												419
#define INVALID_FORM_STREET_LENGTH											420
#define FORM_HOME_NUMBER_NOT_FOUND											421
#define INVALID_FORM_HOME_NUMBER_LENGTH											422
#define FORM_COMPLEMENT_NOT_FOUND											423
#define INVALID_FORM_COMPLEMENT_LENGTH											424
#define FORM_DISTRICT_NOT_FOUND												425
#define INVALID_FORM_DISTRICT_LENGTH											426
#define FORM_CITY_NOT_FOUND												427
#define INVALID_FORM_CITY_LENGTH											428
#define FORM_STATE_NOT_FOUND												429
#define INVALID_FORM_STATE_LENGTH											430
#define FORM_COUNTRY_NOT_FOUND												431
#define INVALID_FORM_COUNTRY_LENGTH											432
#define FORM_ZIP_CODE_NOT_FOUND												433
#define INVALID_FORM_ZIP_CODE_LENGTH											434
#define FORM_GENDER_NOT_FOUND												435
#define INVALID_FORM_GENDER_LENGTH											436
#define FORM_RELATIONSHIP_STATUS_NOT_FOUND										437
#define INVALID_FORM_RELATIONSHIP_STATUS_LENGTH										438
#define FORM_BIRTHDAY_NOT_FOUND												439
#define INVALID_FORM_BIRTHDAY_LENGTH											440
#define FORM_DESCRIPTION_NOT_FOUND											441
#define INVALID_FORM_DESCRIPTION_LENGTH											442
#define FORM_TEL_NUMBER_NOT_FOUND											443
#define INVALID_FORM_TEL_NUMBER_LENGTH											444
#define FORM_CELL_NUMBER_NOT_FOUND											445
#define INVALID_FORM_CELL_NUMBER_LENGTH											446
#define ADD_PARENT_RELATIONSHIP__GIVEN_SON_HAS_NO_GENDER_ANSWERED							447
#define EDIT_PARENT_RELATIONSHIP__GIVEN_NEW_SON_HAS_NO_GENDER_ANSWERED							448
#define GET_USER_FAMILY__ERROR_OPENING_PARENTS_FILE_FOR_READING								449
#define GET_USER_FAMILY__PARENTS_FILE_DOES_NOT_EXIST									450
#define GET_USER_FAMILY__MEMORY_ALLOCATION_ERROR									451
#define GET_USER_FAMILY__USER_HAS_NO_GENDER_ANSWERED									452
#define GET_USER_FAMILY__NO_FAMILY											453
#define GET_USER_FAMIlY__ERROR_OPENING_FAMILY_FILE_FOR_WRITING								454
#define MOUNT_FAMILY_TREE__NO_USER_FAMILY										455
#define RELATIONSHIP_SYSTEM__NB_ARGS_OF_MOUNT_OPTION									456
#define YOU_CAN_ONLY_MOUNT_YOUR_OWN_FAMILY										457




/*---------------------------------------------------------------------------------------------------------*/
char *showTextErrorMessage (unsigned errorCode);
/* 	
INPUT ARGUMENTS
	- unsigned errorCode 
 
DESCRIPTION
	The showTextErrorMessage() function reads the errorCode input argument and returns the corresponding text error message.
	
RETURNED VALUES
	The showTextErrorMessage() function returns a text error message string. 
*/
/*---------------------------------------------------------------------------------------------------------*/

/*---------------------------------------------------------------------------------------------------------*/
char *showHtmlErrorMessage (unsigned errorCode);
/* 	
INPUT ARGUMENTS
	- unsigned errorCode 
 
DESCRIPTION
	The showHtmlErrorMessage() function reads the errorCode input argument and returns the corresponding html error message.
	
RETURNED VALUES
	The showHtmlErrorMessage() function returns a html error message string. 
*/
/*---------------------------------------------------------------------------------------------------------*/

/*---------------------------------------------------------------------------------------------------------*/
void showHtmlErrorPage (unsigned errorCode);
/* 	
INPUT ARGUMENTS
	- unsigned errorCode 
 
DESCRIPTION
	The showHtmlErrorPage() function reads the errorCode input argument and shows the corresponding html error page.
*/
/*---------------------------------------------------------------------------------------------------------*/


#endif

// $RCSfile: error.h,v $
